// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_example_api_key', // Replace with actual API key
    appId: '1:123456789:android:abcdef123456', // Replace with actual app ID
    messagingSenderId: '123456789', // Replace with actual sender ID
    projectId: 'dartlog1',
    storageBucket: 'dartlog1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_example_api_key', // Replace with actual API key
    appId: '1:123456789:ios:abcdef123456', // Replace with actual app ID
    messagingSenderId: '123456789', // Replace with actual sender ID
    projectId: 'dartlog1',
    storageBucket: 'dartlog1.appspot.com',
    iosBundleId: 'com.example.dartin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_example_api_key', // Replace with actual API key
    appId: '1:123456789:macos:abcdef123456', // Replace with actual app ID
    messagingSenderId: '123456789', // Replace with actual sender ID
    projectId: 'dartlog1',
    storageBucket: 'dartlog1.appspot.com',
    iosBundleId: 'com.example.dartin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_example_api_key', // Replace with actual API key
    appId: '1:123456789:web:abcdef123456', // Replace with actual app ID
    messagingSenderId: '123456789', // Replace with actual sender ID
    projectId: 'dartlog1',
    storageBucket: 'dartlog1.appspot.com',
    authDomain: 'dartlog1.firebaseapp.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_example_api_key', // Replace with actual API key
    appId: '1:123456789:windows:abcdef123456', // Replace with actual app ID
    messagingSenderId: '123456789', // Replace with actual sender ID
    projectId: 'dartlog1',
    storageBucket: 'dartlog1.appspot.com',
  );
}